development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  database: db_name
  pool: 5
  username: username
  password: password
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  database: db_name
  pool: 5
  username: username
  password: password
  host: localhost
  port: 3306

production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  database: db_name
  pool: 5
  username: username
  password: password
  host: localhost
  port: 3306
